### ISSUE TITLE
Updates for PiMusicbox v0.7

### ISSUE THREAD

**Issue by kingosticks** [pimusicbox/mopidy-websettings#24]
For tracking any extra options or update labels required for 0.7

- [x] [wifi_country dropdown](https://github.com/pimusicbox/pimusicbox/issues/423)
- [x] [hex wifi_password support label](https://github.com/pimusicbox/pimusicbox/issues/421)
- [ ] ~~[Spotify user_country dropdown](https://github.com/pimusicbox/pimusicbox/commit/c02d4de09936fbfd71669db516e98237550f13ed)~~ (reverted)
- [x] [mpd-watchdog service](https://github.com/pimusicbox/pimusicbox/issues/224)
- [x] [spotify_connect slider](https://github.com/pimusicbox/pimusicbox/issues/332)
